name: Docker Build e Push da imagem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build e push do Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./nola-frontend
        file: ./nola-frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nola-frontend:latest
        build-args: |
          VITE_CUBEJS_TOKEN=${{ secrets.VITE_CUBEJS_TOKEN }}
          VITE_API_URL=${{ secrets.VITE_API_URL }}

    - name: Build e push do Backend
      uses: docker/build-push-action@v4
      with:
        context: ./nola-backend
        file: ./nola-backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nola-backend:latest
        build-args: |
          CUBEJS_API_SECRET=${{ secrets.CUBEJS_API_SECRET }}